name: givethem
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dartz: ^0.9.0-dev.6
  freezed_annotation: ^0.7.1
  flutter_bloc: ^3.2.0
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  flushbar: ^1.10.4
  uuid: ^2.1.0
  auto_route: ^0.5.0
  json_annotation: ^3.0.1
  flutter_svg: ^0.17.4
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  build_runner:
  freezed: ^0.10.6
  lint: ^1.2.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.5.0
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/goals/
